### ISSUE TITLE
Design changes

### ISSUE THREAD

**Issue by addiinnocent** [toplocs/tribelike#38]
Should we change the design to something more functional with clear spaces for the plugins to fit in (Sidebar, Subheader, etc.)? How would it be like?

**Comment by felixboehm** [comment]
We decided to be very similar to github design.

**Comment by addiinnocent** [comment]
<img width="1048" alt="Screenshot 2024-10-02 at 18 43 31" src="https://github.com/user-attachments/assets/f731eb74-547c-4a11-8832-5a11a553901a">
